Traceback (most recent call last):
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 325, in _call_converter
    return self._converter(value)
TypeError: smirks() missing 2 required positional arguments: 'attr' and 'smirks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jessica/miniconda3/envs/openff-dev/bin/ForceBalance.py", line 39, in Run_ForceBalance
    forcefield  = FF(options)
  File "/Users/jessica/miniconda3/envs/openff-dev/lib/python3.7/site-packages/forcebalance/forcefield.py", line 289, in __init__
    self.addff(fnm)
  File "/Users/jessica/miniconda3/envs/openff-dev/lib/python3.7/site-packages/forcebalance/forcefield.py", line 461, in addff
    allow_cosmetic_attributes=True)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 288, in __init__
    self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 755, in parse_sources
    allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 897, in _load_smirnoff_data
    allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 1616, in _add_parameters
    allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 1466, in __init__
    super().__init__(allow_cosmetic_attributes=allow_cosmetic_attributes, **kwargs)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 665, in __init__
    setattr(self, key, val)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 922, in __setattr__
    super().__setattr__(key, value)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 280, in __set__
    value = self._convert_and_validate(instance, value)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 298, in _convert_and_validate
    value = self._call_converter(value, instance)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 328, in _call_converter
    return self._converter(instance, self, value)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 1447, in smirks
    smirks, validate_valence_type=True)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/chemistry/environment.py", line 159, in validate_smirks
    toolkit_registry=toolkit_registry)
  File "/Users/jessica/Documents/Grad_research/WBO_Torsions_ChayaPaper/openforcefield/openforcefield/typing/chemistry/environment.py", line 100, in __init__
    self.validate(validate_valence_type=validate_valence_type, toolkit_registry=toolkit_registry)
TypeError: cached_validate() got an unexpected keyword argument 'validate_valence_type'
